# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refresh_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('secret', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=16)),
                ('redirect_uri', models.URLField()),
                ('grant_type', models.PositiveSmallIntegerField(choices=[(0, 'authorization_code'), (1, 'implicit'), (2, 'password'), (3, 'client_credentials')], default=0)),
                ('code_expires_in', models.PositiveIntegerField(default=300)),
                ('access_token_expires_in', models.PositiveIntegerField(default=604800)),
                ('refresh_token_expires_in', models.PositiveIntegerField(default=2592000)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('redirect_uri', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='scopes',
            field=models.ManyToManyField(to='oauth2.Scope'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
